### ISSUE TITLE
windows中文乱码

### ISSUE THREAD

**Issue by liuyanchen1994** [AntiSomnus/iDict-cmd#1]
![image](https://user-images.githubusercontent.com/19524048/46239235-60d13900-c3c8-11e8-9d11-691380bea27c.png)

**Comment by taoxinyi** [comment]
你好 能否提供下系统版本和默认语言 以及试验下在powershell下是否有乱码的现象 谢谢！

**Comment by liuyanchen1994** [comment]
![image](https://user-images.githubusercontent.com/19524048/46239690-86614100-c3ce-11e8-8218-a33025eb00c6.png)

**Comment by liuyanchen1994** [comment]
powershell也有乱码

**Comment by taoxinyi** [comment]
你打开新的cmd窗口 执行下chcp 然后执行idict welcome 然后再执行chcp 然后把这三条命令的结果截图下 谢谢！

**Comment by liuyanchen1994** [comment]
![image](https://user-images.githubusercontent.com/19524048/46239976-0d181d00-c3d3-11e8-8ad0-22ace01dd074.png)

**Comment by liuyanchen1994** [comment]
c++我不会，只能提issue了

**Comment by taoxinyi** [comment]
我感觉这不是c++的问题 而是编码的问题 65001是UTF8编码 936是GB2312编码 讲道理改成UTF8后都能正确显示 我这里5台的Win10机器都测试没乱码 要不你尝试下修改下cmd内的字体？ 如果还是有问题 你加下我的QQ 850804004
